/* eslint-disable */

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getAppState: () => typedError<AppStateView, string>(__TAURI_INVOKE("get_app_state")),
	unlock: (password: string) => typedError<AppStateView, string>(__TAURI_INVOKE("unlock", { password })),
	lock: () => typedError<AppStateView, string>(__TAURI_INVOKE("lock")),
	changePassword: (oldPassword: string, newPassword: string) => typedError<AppStateView, string>(__TAURI_INVOKE("change_password", { oldPassword, newPassword })),
	getBootId: () => typedError<string, string>(__TAURI_INVOKE("get_boot_id")),
	setAutoLockMode: (mode: string) => typedError<AppStateView, string>(__TAURI_INVOKE("set_auto_lock_mode", { mode })),
	simulateOsSuspendCmd: () => typedError<null, string>(__TAURI_INVOKE("simulate_os_suspend_cmd")),
	armUpdateWatchdogCmd: (targetVersion: string) => typedError<null, string>(__TAURI_INVOKE("arm_update_watchdog_cmd", { targetVersion })),
	disarmUpdateWatchdogCmd: () => typedError<null, string>(__TAURI_INVOKE("disarm_update_watchdog_cmd")),
	getRollbackNoticeCmd: () => typedError<string | null, string>(__TAURI_INVOKE("get_rollback_notice_cmd")),
	createVault: (name: string, path: string) => typedError<AppStateView, string>(__TAURI_INVOKE("create_vault", { name, path })),
	createAccount: (username: string, password: string, templateLanguage: string | null, accountProfile: string | null) => typedError<AppStateView, string>(__TAURI_INVOKE("create_account", { username, password, templateLanguage, accountProfile })),
	importVault: (path: string, password: string) => typedError<AppStateView, string>(__TAURI_INVOKE("import_vault", { path, password })),
	inspectVaultFolder: (path: string) => typedError<VaultInspectionResult, string>(__TAURI_INVOKE("inspect_vault_folder", { path })),
	getPendingImportPath: () => __TAURI_INVOKE<string | null>("get_pending_import_path"),
	clearPendingImportPath: () => __TAURI_INVOKE<void>("clear_pending_import_path"),
	deleteVaultAndAccount: (password: string) => typedError<AppStateView, string>(__TAURI_INVOKE("delete_vault_and_account", { password })),
	openVaultFolder: () => typedError<null, string>(__TAURI_INVOKE("open_vault_folder")),
	exportTextFile: (path: string, contents: string) => typedError<null, string>(__TAURI_INVOKE("export_text_file", { path, contents })),
	getKnownVaultsCmd: () => typedError<VaultRegistryEntry[], string>(__TAURI_INVOKE("get_known_vaults_cmd")),
	rememberKnownVaultCmd: (entry: VaultRegistryEntry) => typedError<null, string>(__TAURI_INVOKE("remember_known_vault_cmd", { entry })),
	forgetKnownVaultCmd: (idOrPath: string) => typedError<null, string>(__TAURI_INVOKE("forget_known_vault_cmd", { idOrPath })),
	setActiveVault: (path: string) => typedError<AppStateView, string>(__TAURI_INVOKE("set_active_vault", { path })),
	exportVaultBackupFolder: (destDir: string) => typedError<null, string>(__TAURI_INVOKE("export_vault_backup_folder", { destDir })),
	renameUser: (username: string) => typedError<AppStateView, string>(__TAURI_INVOKE("rename_user", { username })),
	renameVault: (name: string) => typedError<AppStateView, string>(__TAURI_INVOKE("rename_vault", { name })),
	writeFileRaw: (path: string, contents: number[]) => typedError<null, string>(__TAURI_INVOKE("write_file_raw", { path, contents })),
	createAccountCmd: (input: CreateAccountInput) => typedError<Account, AppErrorDto>(__TAURI_INVOKE("create_account_cmd", { input })),
	updateAccountCmd: (id: string, input: UpdateAccountInput) => typedError<Account, AppErrorDto>(__TAURI_INVOKE("update_account_cmd", { id, input })),
	deleteAccountCmd: (id: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("delete_account_cmd", { id })),
	getAccountCmd: (id: string) => typedError<Account, AppErrorDto>(__TAURI_INVOKE("get_account_cmd", { id })),
	listAccountsCmd: () => typedError<AccountBalanceView[], AppErrorDto>(__TAURI_INVOKE("list_accounts_cmd")),
	seedRootAccountsCmd: () => typedError<Account[], AppErrorDto>(__TAURI_INVOKE("seed_root_accounts_cmd")),
	seedStarterAccountsCmd: (language: string | null, profile: string | null) => typedError<Account[], AppErrorDto>(__TAURI_INVOKE("seed_starter_accounts_cmd", { language, profile })),
	postJournalEntryCmd: (input: CreateJournalEntryInput) => typedError<JournalEntryView, AppErrorDto>(__TAURI_INVOKE("post_journal_entry_cmd", { input })),
	updateJournalEntryCmd: (id: string, input: UpdateJournalEntryInput) => typedError<JournalEntryView, AppErrorDto>(__TAURI_INVOKE("update_journal_entry_cmd", { id, input })),
	deleteJournalEntryCmd: (id: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("delete_journal_entry_cmd", { id })),
	getJournalEntryCmd: (id: string) => typedError<JournalEntryView, AppErrorDto>(__TAURI_INVOKE("get_journal_entry_cmd", { id })),
	listJournalEntriesCmd: (limit: number | null, offset: number | null) => typedError<JournalEntryView[], AppErrorDto>(__TAURI_INVOKE("list_journal_entries_cmd", { limit, offset })),
	getAccountLedgerCmd: (accountId: string) => typedError<AccountRunningLedgerItem[], AppErrorDto>(__TAURI_INVOKE("get_account_ledger_cmd", { accountId })),
	getLedgerTotalsCmd: (fxRate: number | null) => typedError<LedgerTotalsView, AppErrorDto>(__TAURI_INVOKE("get_ledger_totals_cmd", { fxRate })),
	getDashboardMetricsCmd: (fxRate: number | null, today: string | null) => typedError<DashboardMetricsView, AppErrorDto>(__TAURI_INVOKE("get_dashboard_metrics_cmd", { fxRate, today })),
	diagnoseVaultHealthCmd: () => typedError<VaultHealthReport, AppErrorDto>(__TAURI_INVOKE("diagnose_vault_health_cmd")),
	getClosingDateCmd: () => typedError<string | null, AppErrorDto>(__TAURI_INVOKE("get_closing_date_cmd")),
	setClosingDateCmd: (closingDate: string | null) => typedError<null, AppErrorDto>(__TAURI_INVOKE("set_closing_date_cmd", { closingDate })),
	exportBeancountCmd: (path: string | null) => typedError<string, AppErrorDto>(__TAURI_INVOKE("export_beancount_cmd", { path })),
	upsertBudgetCmd: (input: UpsertBudgetInput) => typedError<BudgetAllocation, AppErrorDto>(__TAURI_INVOKE("upsert_budget_cmd", { input })),
	deleteBudgetCmd: (id: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("delete_budget_cmd", { id })),
	getBudgetSummaryCmd: (month: string) => typedError<BudgetMonthSummary, AppErrorDto>(__TAURI_INVOKE("get_budget_summary_cmd", { month })),
	getAuditLogCmd: (page: number, perPage: number) => typedError<AuditPage, AppErrorDto>(__TAURI_INVOKE("get_audit_log_cmd", { page, perPage })),
	getEntityAuditLogCmd: (entityType: string, entityId: string) => typedError<AuditEntry[], AppErrorDto>(__TAURI_INVOKE("get_entity_audit_log_cmd", { entityType, entityId })),
	verifyAuditLogIntegrityCmd: () => typedError<AuditIntegrityReport, AppErrorDto>(__TAURI_INVOKE("verify_audit_log_integrity_cmd")),
	createPlanCmd: (input: CreatePlanInput) => typedError<PaymentPlan, AppErrorDto>(__TAURI_INVOKE("create_plan_cmd", { input })),
	updatePlanCmd: (id: string, input: UpdatePlanInput) => typedError<PaymentPlan, AppErrorDto>(__TAURI_INVOKE("update_plan_cmd", { id, input })),
	deletePlanCmd: (id: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("delete_plan_cmd", { id })),
	getPlanCmd: (id: string) => typedError<PaymentPlan, AppErrorDto>(__TAURI_INVOKE("get_plan_cmd", { id })),
	listPlansCmd: () => typedError<PaymentPlan[], AppErrorDto>(__TAURI_INVOKE("list_plans_cmd")),
	listPlansWithProgressCmd: () => typedError<PlanProgressView[], AppErrorDto>(__TAURI_INVOKE("list_plans_with_progress_cmd")),
	recordPlanInstallmentCmd: (input: RecordInstallmentInput) => typedError<JournalEntryView, AppErrorDto>(__TAURI_INVOKE("record_plan_installment_cmd", { input })),
	getDueRecurringPlansCmd: (asOfDate: string | null) => typedError<DueRecurringPlanView[], AppErrorDto>(__TAURI_INVOKE("get_due_recurring_plans_cmd", { asOfDate })),
	postDueRecurringBatchCmd: (input: PostDueRecurringBatchInput) => typedError<JournalEntryView[], AppErrorDto>(__TAURI_INVOKE("post_due_recurring_batch_cmd", { input })),
	getReconciliationStatusCmd: (accountId: string) => typedError<ReconciliationStatusView, AppErrorDto>(__TAURI_INVOKE("get_reconciliation_status_cmd", { accountId })),
	setPostingReconciledCmd: (postingId: string, status: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("set_posting_reconciled_cmd", { postingId, status })),
	bulkSetPostingsReconciledCmd: (postingIds: string[], status: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("bulk_set_postings_reconciled_cmd", { postingIds, status })),
	finishReconciliationCmd: (accountId: string, postingIds: string[]) => typedError<null, AppErrorDto>(__TAURI_INVOKE("finish_reconciliation_cmd", { accountId, postingIds })),
	matchStatementCmd: (accountId: string, statements: StatementRow[], autoClear: boolean) => typedError<MatchStatementOutput, AppErrorDto>(__TAURI_INVOKE("match_statement_cmd", { accountId, statements, autoClear })),
	readStatementFileCmd: (path: string) => typedError<string, AppErrorDto>(__TAURI_INVOKE("read_statement_file_cmd", { path })),
	listReconcileRulesCmd: () => typedError<ReconcileRuleWithAccount[], AppErrorDto>(__TAURI_INVOKE("list_reconcile_rules_cmd")),
	createReconcileRuleCmd: (input: CreateReconcileRuleInput) => typedError<ReconcileRuleWithAccount, AppErrorDto>(__TAURI_INVOKE("create_reconcile_rule_cmd", { input })),
	deleteReconcileRuleCmd: (ruleId: string) => typedError<null, AppErrorDto>(__TAURI_INVOKE("delete_reconcile_rule_cmd", { ruleId })),
	evaluateReconcileRulesCmd: (statements: StatementRow[]) => typedError<StatementRow[], AppErrorDto>(__TAURI_INVOKE("evaluate_reconcile_rules_cmd", { statements })),
	getProfitLossReportCmd: (fromDate: string | null, toDate: string | null) => typedError<ProfitLossReport, AppErrorDto>(__TAURI_INVOKE("get_profit_loss_report_cmd", { fromDate, toDate })),
	getBalanceSheetReportCmd: (asOfDate: string | null) => typedError<BalanceSheetReport, AppErrorDto>(__TAURI_INVOKE("get_balance_sheet_report_cmd", { asOfDate })),
	getCashFlowReportCmd: (fromDate: string | null, toDate: string | null) => typedError<CashFlowReport, AppErrorDto>(__TAURI_INVOKE("get_cash_flow_report_cmd", { fromDate, toDate })),
	getTrialBalanceReportCmd: (asOfDate: string | null) => typedError<TrialBalanceReport, AppErrorDto>(__TAURI_INVOKE("get_trial_balance_report_cmd", { asOfDate })),
	getFxRevaluationReportCmd: (asOfDate: string | null, fxRate: number | null) => typedError<FxRevaluationReport, AppErrorDto>(__TAURI_INVOKE("get_fx_revaluation_report_cmd", { asOfDate, fxRate })),
	getHistoricalTrendsReportCmd: (fromDate: string, toDate: string, fxRate: number | null) => typedError<HistoricalTrendsReport, AppErrorDto>(__TAURI_INVOKE("get_historical_trends_report_cmd", { fromDate, toDate, fxRate })),
	getMonthlyCashflowSummaryCmd: (months: number | null) => typedError<MonthlyCashflowPoint[], AppErrorDto>(__TAURI_INVOKE("get_monthly_cashflow_summary_cmd", { months })),
};

/* Types */
export type Account = {
	id: string,
	code: string,
	name: string,
	account_type: AccountType,
	parent_id: string | null,
	currency: string,
	placeholder: boolean,
	hidden: boolean,
	color: string | null,
	note: string | null,
	description: string | null,
	interest_rate: number | null,
	created_at: number,
};

export type AccountBalanceView = {
	account: Account,
	direct_balance: number,
	recursive_balance: number,
};

export type AccountReportRow = {
	account_id: string,
	code: string,
	name: string,
	currency: string,
	amount: number,
};

export type AccountRunningLedgerItem = {
	posting_id: string,
	entry_id: string,
	date: string,
	description: string,
	amount: number,
	running_balance: number,
	reconcile: ReconcileState,
	memo: string | null,
	offset_account: string | null,
};

export type AccountType = "ASSET" | "LIABILITY" | "EQUITY" | "INCOME" | "EXPENSE";

export type AppErrorDto = {
	code: string,
	message: string,
};

export type AppStateView = {
	configured: boolean,
	unlocked: boolean,
	username: string | null,
	vault_name: string | null,
	vault_path: string | null,
	settings: Settings,
	pending_import_path: string | null,
};

export type AuditEntry = {
	id: string,
	actor: string,
	action: string,
	entity_type: string,
	entity_id: string,
	detail: string | null,
	created_at: number,
	prev_hash: string | null,
	hash: string | null,
};

export type AuditIntegrityReport = {
	is_valid: boolean,
	total_verified: number,
	broken_index: number | null,
	error_message: string | null,
};

export type AuditPage = {
	entries: AuditEntry[],
	total: number,
	page: number,
	per_page: number,
};

export type BalanceSheetReport = {
	as_of_date: string | null,
	asset_rows: AccountReportRow[],
	liability_rows: AccountReportRow[],
	equity_rows: AccountReportRow[],
	total_assets: number,
	total_liabilities: number,
	total_equity: number,
	net_income: number,
	discrepancy: number,
	is_balanced: boolean,
};

export type BudgetAllocation = {
	id: string,
	month: string,
	account_id: string,
	amount: number,
	created_at: number,
};

export type BudgetMonthSummary = {
	month: string,
	envelopes: EnvelopeView[],
	total_assigned: number,
	total_activity: number,
	to_be_budgeted: number,
};

export type CashFlowActivityRow = {
	date: string,
	category: string,
	description: string,
	account_name: string,
	amount: number,
};

export type CashFlowReport = {
	from_date: string | null,
	to_date: string | null,
	starting_cash: number,
	operating_cash_flow: number,
	investing_cash_flow: number,
	financing_cash_flow: number,
	net_cash_change: number,
	ending_cash: number,
	operating_rows: CashFlowActivityRow[],
	investing_rows: CashFlowActivityRow[],
	financing_rows: CashFlowActivityRow[],
};

export type CreateAccountInput = {
	code: string,
	name: string,
	account_type: AccountType,
	parent_id?: string | null,
	currency?: string | null,
	placeholder?: boolean | null,
	hidden?: boolean | null,
	color?: string | null,
	note?: string | null,
	description?: string | null,
	interest_rate?: number | null,
};

export type CreateJournalEntryInput = {
	id?: string | null,
	date: string,
	description: string,
	notes?: string | null,
	reference_no?: string | null,
	due_date?: string | null,
	plan_id?: string | null,
	currency?: string | null,
	fx_rate?: number | null,
	postings: PostingInput[],
};

export type CreatePlanInput = {
	title: string,
	plan_type: PlanType,
	status?: PlanStatus | null,
	total_amount: number,
	installment_amount: number,
	frequency: PlanFrequency,
	start_date: string,
	due_date?: string | null,
	day_of_month?: number | null,
	from_account_id: string,
	to_account_id: string,
	notes?: string | null,
	last_posted_date?: string | null,
	auto_post?: boolean | null,
};

export type CreateReconcileRuleInput = {
	pattern: string,
	is_regex: boolean,
	match_type: string | null,
	account_id: string,
	priority: number | null,
	description_override: string | null,
};

export type DailyTrendPoint = {
	date: string,
	net_worth: number,
	assets: number,
	liabilities: number,
	liquid_cash: number,
};

export type DashboardMetricsView = {
	total_assets: number,
	total_liabilities: number,
	net_worth: number,
	monthly_burn_30d: number,
	runway_months: number | null,
	this_month_income: number,
	this_month_expense: number,
	this_month_net: number,
	overdue_invoices_count: number,
	overdue_invoices_amount: number,
	upcoming_due_count: number,
	upcoming_due_amount: number,
};

export type DueRecurringPlanView = {
	plan_id: string,
	title: string,
	plan_type: PlanType,
	amount: number,
	currency: string,
	from_account_id: string,
	from_account_name: string,
	to_account_id: string,
	to_account_name: string,
	next_due_date: string,
	is_overdue: boolean,
	days_diff: number,
	last_posted_date: string | null,
};

export type EnvelopeView = {
	account_id: string,
	account_code: string,
	account_name: string,
	assigned: number,
	activity: number,
	available: number,
};

export type FxRevaluationItem = {
	account_id: string,
	code: string,
	name: string,
	currency: string,
	native_balance: number,
	cost_basis_idr: number,
	current_value_idr: number,
	unrealized_gain_idr: number,
};

export type FxRevaluationReport = {
	as_of_date: string | null,
	current_fx_rate: number,
	items: FxRevaluationItem[],
	total_cost_basis_idr: number,
	total_current_value_idr: number,
	total_unrealized_gain_idr: number,
};

export type HistoricalTrendsReport = {
	from_date: string,
	to_date: string,
	points: DailyTrendPoint[],
};

export type JournalEntryView = {
	id: string,
	date: string,
	description: string,
	notes: string | null,
	reference_no: string | null,
	due_date: string | null,
	plan_id: string | null,
	currency: string,
	fx_rate: number,
	posted_at: number,
	postings: PostingView[],
};

export type LedgerTotalsView = {
	total_assets: number,
	total_liabilities: number,
	total_equity: number,
	total_income: number,
	total_expenses: number,
	net_income: number,
	balance_sheet_discrepancy: number,
	is_balance_sheet_aligned: boolean,
};

export type MatchResult = {
	statement_index: number,
	posting_id: string,
	matched_amount: number,
	confidence: number,
	days_diff: number,
	matched_description: string | null,
};

export type MatchStatementOutput = {
	matches: MatchResult[],
	unmatched_statement_indices: number[],
	unmatched_statement_rows: StatementRow[],
	matched_count: number,
	unmatched_count: number,
};

export type MatchedRuleSuggestion = {
	rule_id: string,
	pattern: string,
	account_id: string,
	account_code: string,
	account_name: string,
	description_override: string | null,
};

export type MonthlyCashflowPoint = {
	month: string,
	income: number,
	expense: number,
	net: number,
};

export type PaymentPlan = {
	id: string,
	title: string,
	plan_type: PlanType,
	status: PlanStatus,
	total_amount: number,
	installment_amount: number,
	frequency: PlanFrequency,
	start_date: string,
	due_date: string | null,
	day_of_month: number | null,
	from_account_id: string,
	to_account_id: string,
	notes: string | null,
	last_posted_date: string | null,
	auto_post: boolean,
	created_at: number,
};

export type PlanFrequency = "DAILY" | "WEEKLY" | "MONTHLY";

export type PlanProgressView = {
	plan: PaymentPlan,
	paid_amount: number,
	remaining_amount: number,
	progress_percent: number,
	is_settled: boolean,
	installments_paid_count: number,
};

export type PlanStatus = "ACTIVE" | "COMPLETED" | "OVERDUE" | "ARCHIVED";

export type PlanType = "RECEIVABLE" | "PAYABLE" | "RECURRING";

export type PostDueRecurringBatchInput = {
	plan_ids: string[],
	date?: string | null,
};

export type PostingInput = {
	id?: string | null,
	account_id: string,
	amount: number,
	memo?: string | null,
	action?: string | null,
	reconcile?: ReconcileState | null,
	currency?: string | null,
	fx_rate?: number | null,
	cost_amount?: number | null,
};

export type PostingReconcileView = {
	posting_id: string,
	entry_id: string,
	date: string,
	description: string,
	amount: number,
	memo: string | null,
	reconciled: string,
	reconciled_at: number | null,
};

export type PostingView = {
	id: string,
	entry_id: string,
	account_id: string,
	account_code: string,
	account_name: string,
	account_type: AccountType,
	amount: number,
	memo: string | null,
	action: string | null,
	reconcile: ReconcileState,
	reconciled_at: number | null,
	currency: string,
	fx_rate: number | null,
	cost_amount: number | null,
};

export type ProfitLossReport = {
	from_date: string | null,
	to_date: string | null,
	income_rows: AccountReportRow[],
	expense_rows: AccountReportRow[],
	total_income: number,
	total_expenses: number,
	net_income: number,
};

export type ReconcileRuleWithAccount = {
	id: string,
	pattern: string,
	is_regex: boolean,
	match_type: string,
	account_id: string,
	account_code: string,
	account_name: string,
	account_type: string,
	priority: number,
	description_override: string | null,
	created_at: number,
};

export type ReconcileState = "n" | "c" | "y";

export type ReconciliationStatusView = {
	account_id: string,
	reconciled_balance: number,
	cleared_balance: number,
	uncleared_balance: number,
	total_balance: number,
	uncleared_postings: PostingReconcileView[],
};

export type RecordInstallmentInput = {
	plan_id: string,
	date: string,
	amount: number,
	reference_no?: string | null,
	notes?: string | null,
};

export type Settings = {
	auto_lock_mode: string,
	/**  Linux boot_id at time mode was set to on-reboot — for fast-unlock comparison */
	boot_id?: string | null,
};

export type StatementRow = {
	date: string,
	amount: number,
	description?: string | null,
	rule_match?: MatchedRuleSuggestion | null,
};

export type TrialBalanceReport = {
	as_of_date: string | null,
	rows: TrialBalanceRow[],
	total_debit: number,
	total_credit: number,
	is_balanced: boolean,
};

export type TrialBalanceRow = {
	account_id: string,
	code: string,
	name: string,
	account_type: string,
	currency: string,
	debit: number,
	credit: number,
};

export type UpdateAccountInput = {
	code?: string | null,
	name?: string | null,
	account_type?: AccountType | null,
	parent_id?: string | null,
	currency?: string | null,
	placeholder?: boolean | null,
	hidden?: boolean | null,
	color?: string | null,
	note?: string | null,
	description?: string | null,
	interest_rate?: number | null,
};

export type UpdateJournalEntryInput = {
	date?: string | null,
	description?: string | null,
	notes?: string | null,
	reference_no?: string | null,
	due_date?: string | null,
	plan_id?: string | null,
	currency?: string | null,
	fx_rate?: number | null,
	postings?: PostingInput[] | null,
};

export type UpdatePlanInput = {
	title?: string | null,
	plan_type?: PlanType | null,
	status?: PlanStatus | null,
	total_amount?: number | null,
	installment_amount?: number | null,
	frequency?: PlanFrequency | null,
	start_date?: string | null,
	due_date?: string | null,
	day_of_month?: number | null,
	from_account_id?: string | null,
	to_account_id?: string | null,
	notes?: string | null,
	last_posted_date?: string | null,
	auto_post?: boolean | null,
};

export type UpsertBudgetInput = {
	id?: string | null,
	month: string,
	account_id: string,
	amount: number,
};

export type VaultHealthReport = {
	is_healthy: boolean,
	sqlite_integrity: string,
	foreign_keys_ok: boolean,
	unbalanced_entries_count: number,
	orphan_postings_count: number,
	placeholder_postings_count: number,
	issues: string[],
};

export type VaultInspectionResult = {
	status: string,
	vault_name: string | null,
	username: string | null,
	is_valid: boolean,
	message: string,
};

export type VaultRegistryEntry = {
	id: string,
	name: string,
	path: string,
	username: string,
	last_opened_at?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

