use crate::accounts::models::{Account, AccountType};
use crate::ledger::dto::PostingView;
use crate::ledger::models::ReconcileState;
use crate::shared::AppError;
use rusqlite::Connection;
use std::collections::{HashMap, HashSet};
use std::str::FromStr;

pub fn sanitize_component(name: &str) -> String {
    let mut res = String::new();
    let mut last_dash = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            res.push(ch);
            last_dash = false;
        } else if !last_dash && !res.is_empty() {
            res.push('-');
            last_dash = true;
        }
    }
    let trimmed = res.trim_end_matches('-').to_string();
    if trimmed.is_empty() {
        "Unknown".to_string()
    } else {
        let mut chars = trimmed.chars();
        if let Some(first) = chars.next() {
            if first.is_ascii_lowercase() {
                format!("{}{}", first.to_ascii_uppercase(), chars.as_str())
            } else if first.is_ascii_uppercase() || first.is_ascii_digit() {
                trimmed
            } else {
                format!("A{}", trimmed)
            }
        } else {
            "Unknown".to_string()
        }
    }
}

pub fn format_beancount_account_name(
    acc: &Account,
    accounts_by_id: &HashMap<String, Account>,
) -> String {
    let root_category = match acc.account_type {
        AccountType::Asset => "Assets",
        AccountType::Liability => "Liabilities",
        AccountType::Equity => "Equity",
        AccountType::Income => "Income",
        AccountType::Expense => "Expenses",
    };

    let mut chain = Vec::new();
    let mut current_id = Some(acc.id.clone());
    let mut visited = HashSet::new();

    while let Some(id) = current_id {
        if !visited.insert(id.clone()) {
            break;
        }
        if let Some(a) = accounts_by_id.get(&id) {
            chain.push(a);
            current_id = a.parent_id.clone();
        } else {
            break;
        }
    }
    chain.reverse();

    let mut components = Vec::new();
    components.push(root_category.to_string());

    for a in chain {
        if a.code == "1000"
            || a.code == "2000"
            || a.code == "3000"
            || a.code == "4000"
            || a.code == "5000"
        {
            continue;
        }
        let clean_name = sanitize_component(&a.name);
        let comp = format!("{}-{}", a.code, clean_name);
        components.push(comp);
    }

    if components.len() == 1 {
        let clean_name = sanitize_component(&acc.name);
        components.push(format!("{}-{}", acc.code, clean_name));
    }

    components.join(":")
}

pub fn format_beancount_amount(amount: i64, currency: &str) -> String {
    let curr = currency.trim().to_uppercase();
    let curr_code = if curr.is_empty() { "IDR" } else { &curr };
    if curr_code == "IDR" || curr_code == "JPY" {
        format!("{} {}", amount, curr_code)
    } else {
        let is_neg = amount < 0;
        let abs = amount.unsigned_abs();
        let major = abs / 100;
        let minor = abs % 100;
        let sign = if is_neg { "-" } else { "" };
        format!("{}{}.{:02} {}", sign, major, minor, curr_code)
    }
}

fn escape_beancount_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\r', "")
        .replace('\n', " ")
}

pub fn generate_beancount_export(conn: &Connection) -> Result<String, AppError> {
    let accounts = crate::accounts::repository::list_all(conn)?;
    let mut accounts_by_id: HashMap<String, Account> = HashMap::with_capacity(accounts.len());
    let mut operating_currencies: HashSet<String> = HashSet::new();
    operating_currencies.insert("IDR".to_string());

    for acc in &accounts {
        if !acc.currency.is_empty() {
            operating_currencies.insert(acc.currency.to_uppercase());
        }
        accounts_by_id.insert(acc.id.clone(), acc.clone());
    }

    if let Ok(mut post_curr_stmt) = conn.prepare(
        "SELECT DISTINCT currency FROM postings WHERE currency IS NOT NULL AND currency != '';",
    ) {
        if let Ok(curr_rows) = post_curr_stmt.query_map([], |r| r.get::<_, String>(0)) {
            for c in curr_rows.flatten() {
                operating_currencies.insert(c.to_uppercase());
            }
        }
    }

    let mut out = String::with_capacity(64 * 1024);
    out.push_str(";; -*- mode: beancount; coding: utf-8; -*-\n");
    out.push_str(&format!(
        ";; Generated by {} Desktop — Plain Text Accounting Export\n\n",
        crate::shared::APP_NAME
    ));
    out.push_str(&format!(
        "option \"title\" \"{} Ledger\"\n",
        crate::shared::APP_NAME
    ));

    let mut sorted_currencies: Vec<_> = operating_currencies.into_iter().collect();
    sorted_currencies.sort();
    for curr in &sorted_currencies {
        out.push_str(&format!("option \"operating_currency\" \"{}\"\n", curr));
    }
    out.push('\n');

    for curr in &sorted_currencies {
        out.push_str(&format!("1970-01-01 commodity {}\n", curr));
    }
    out.push('\n');

    for acc in &accounts {
        if acc.placeholder {
            continue;
        }
        let acc_name = format_beancount_account_name(acc, &accounts_by_id);
        let curr = if acc.currency.is_empty() {
            "IDR"
        } else {
            &acc.currency
        };
        out.push_str(&format!("1970-01-01 open {} {}\n", acc_name, curr));
    }
    out.push('\n');

    let mut stmt = conn.prepare(
        "SELECT id, date, description, notes, reference_no, due_date, plan_id, currency, fx_rate, posted_at
         FROM journal_entries
         ORDER BY date ASC, posted_at ASC, id ASC;",
    )?;

    let mut entries = Vec::new();
    let mut entry_rows = stmt.query([])?;
    while let Some(row) = entry_rows.next()? {
        entries.push((
            row.get::<_, String>(0)?,
            row.get::<_, String>(1)?,
            row.get::<_, String>(2)?,
            row.get::<_, Option<String>>(3)?,
            row.get::<_, Option<String>>(4)?,
            row.get::<_, Option<String>>(5)?,
            row.get::<_, Option<String>>(6)?,
            row.get::<_, String>(7)?,
            row.get::<_, i64>(8)?,
            row.get::<_, i64>(9)?,
        ));
    }

    let mut postings_stmt = conn.prepare(
        "SELECT p.id, p.entry_id, p.account_id, a.code, a.name, a.type, p.amount, p.memo, p.action, p.reconciled, p.reconciled_at, p.currency, p.fx_rate, p.cost_amount
         FROM postings p
         JOIN accounts a ON p.account_id = a.id
         ORDER BY p.amount DESC, p.id ASC;",
    )?;

    let mut postings_by_entry: HashMap<String, Vec<PostingView>> = HashMap::new();
    let posting_rows = postings_stmt.query_map([], |row| {
        let type_str: String = row.get(5)?;
        let account_type = AccountType::from_str(&type_str).unwrap_or(AccountType::Asset);
        let rec_str: String = row.get(9)?;
        let reconcile = ReconcileState::from_str(&rec_str).unwrap_or(ReconcileState::None);
        Ok(PostingView {
            id: row.get(0)?,
            entry_id: row.get(1)?,
            account_id: row.get(2)?,
            account_code: row.get(3)?,
            account_name: row.get(4)?,
            account_type,
            amount: row.get(6)?,
            memo: row.get(7)?,
            action: row.get(8)?,
            reconcile,
            reconciled_at: row.get(10)?,
            currency: row.get(11)?,
            fx_rate: row.get(12)?,
            cost_amount: row.get(13)?,
        })
    })?;

    for p_res in posting_rows {
        let p = p_res?;
        postings_by_entry
            .entry(p.entry_id.clone())
            .or_default()
            .push(p);
    }

    for (id, date, desc, notes, ref_no, _due_date, _plan_id, _currency, _fx_rate, _posted_at) in
        entries
    {
        let esc_desc = escape_beancount_string(&desc);
        if let Some(n) = notes.filter(|s| !s.trim().is_empty()) {
            let esc_notes = escape_beancount_string(&n);
            out.push_str(&format!("{} * \"{}\" \"{}\"\n", date, esc_desc, esc_notes));
        } else {
            out.push_str(&format!("{} * \"{}\"\n", date, esc_desc));
        }

        if let Some(r) = ref_no.filter(|s| !s.trim().is_empty()) {
            out.push_str(&format!("  ref: \"{}\"\n", escape_beancount_string(&r)));
        }
        out.push_str(&format!("  finnca_id: \"{}\"\n", id));

        if let Some(postings) = postings_by_entry.get(&id) {
            for post in postings {
                let acc_opt = accounts_by_id.get(&post.account_id);
                let acc_name = if let Some(acc) = acc_opt {
                    format_beancount_account_name(acc, &accounts_by_id)
                } else {
                    format!("Expenses:Unknown-{}", post.account_code)
                };
                let curr = if !post.currency.is_empty() {
                    post.currency.as_str()
                } else {
                    acc_opt.map(|a| a.currency.as_str()).unwrap_or("IDR")
                };
                let amt_str = format_beancount_amount(post.amount, curr);
                let line_str = if let Some(cost) = post.cost_amount {
                    format!(
                        "{} @@ {}",
                        amt_str,
                        format_beancount_amount(cost.abs(), "IDR")
                    )
                } else if curr != "IDR" {
                    if let Some(rate) = post.fx_rate {
                        format!("{} @ {} IDR", amt_str, rate)
                    } else {
                        amt_str
                    }
                } else {
                    amt_str
                };

                if let Some(m) = &post.memo {
                    let trimmed_m = m.trim();
                    if !trimmed_m.is_empty() {
                        out.push_str(&format!(
                            "  {:<50} {:>16} ; {}\n",
                            acc_name, line_str, trimmed_m
                        ));
                    } else {
                        out.push_str(&format!("  {:<50} {:>16}\n", acc_name, line_str));
                    }
                } else {
                    out.push_str(&format!("  {:<50} {:>16}\n", acc_name, line_str));
                }
            }
        }
        out.push('\n');
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::accounts::dto::CreateAccountInput;
    use crate::accounts::models::AccountType;
    use crate::accounts::service::create_account;
    use crate::db::open_vault_db;
    use crate::ledger::dto::{CreateJournalEntryInput, PostingInput};
    use crate::ledger::service::post_journal_entry;

    fn setup_test_db() -> Connection {
        let temp_dir = tempfile::tempdir().expect("tempdir");
        let db_path = temp_dir.path().join("test_beancount.db");
        let dek = [1u8; 32];
        open_vault_db(&db_path, &dek).expect("open test db")
    }

    #[test]
    fn test_sanitize_component() {
        assert_eq!(sanitize_component("Kas & Bank"), "Kas-Bank");
        assert_eq!(
            sanitize_component("Makan / Minum (Kafe)"),
            "Makan-Minum-Kafe"
        );
        assert_eq!(sanitize_component("123 test"), "123-test");
        assert_eq!(sanitize_component("lower case"), "Lower-case");
        assert_eq!(sanitize_component(""), "Unknown");
    }

    #[test]
    fn test_format_beancount_amount() {
        assert_eq!(format_beancount_amount(50000, "IDR"), "50000 IDR");
        assert_eq!(format_beancount_amount(-50000, "IDR"), "-50000 IDR");
        assert_eq!(format_beancount_amount(1550, "USD"), "15.50 USD");
        assert_eq!(format_beancount_amount(-2500, "USD"), "-25.00 USD");
        assert_eq!(format_beancount_amount(5, "USD"), "0.05 USD");
    }

    #[test]
    fn test_generate_beancount_export_full_cycle() {
        let mut conn = setup_test_db();
        let cash = create_account(
            &conn,
            CreateAccountInput {
                code: "1110".into(),
                name: "Kas Operasional".into(),
                account_type: AccountType::Asset,
                parent_id: None,
                currency: Some("IDR".into()),
                placeholder: Some(false),
                hidden: Some(false),
                color: None,
                note: None,
                description: None,
                interest_rate: None,
            },
            "test",
        )
        .expect("create cash account");

        let food = create_account(
            &conn,
            CreateAccountInput {
                code: "5101".into(),
                name: "Makan & Minum".into(),
                account_type: AccountType::Expense,
                parent_id: None,
                currency: Some("IDR".into()),
                placeholder: Some(false),
                hidden: Some(false),
                color: None,
                note: None,
                description: None,
                interest_rate: None,
            },
            "test",
        )
        .expect("create food account");

        post_journal_entry(
            &mut conn,
            CreateJournalEntryInput {
                id: None,
                date: "2026-09-27".into(),
                description: "Makan Siang Tim".into(),
                notes: Some("Pertemuan mingguan".into()),
                reference_no: Some("REF-001".into()),
                due_date: None,
                plan_id: None,
                currency: Some("IDR".into()),
                fx_rate: Some(16000),
                postings: vec![
                    PostingInput {
                        id: None,
                        account_id: food.id.clone(),
                        amount: 75000,
                        memo: Some("Nasi Padang".into()),
                        action: None,
                        reconcile: None,
                        ..Default::default()
                    },
                    PostingInput {
                        id: None,
                        account_id: cash.id.clone(),
                        amount: -75000,
                        memo: Some("Tunai".into()),
                        action: None,
                        reconcile: None,
                        ..Default::default()
                    },
                ],
            },
            "test",
        )
        .expect("post tx");

        let output = generate_beancount_export(&conn).expect("export beancount");
        assert!(output.contains("option \"operating_currency\" \"IDR\""));
        assert!(output.contains("1970-01-01 open Assets:1110-Kas-Operasional IDR"));
        assert!(output.contains("1970-01-01 open Expenses:5101-Makan-Minum IDR"));
        assert!(output.contains("2026-09-27 * \"Makan Siang Tim\" \"Pertemuan mingguan\""));
        assert!(output.contains("ref: \"REF-001\""));
        assert!(output.contains("Assets:1110-Kas-Operasional"));
        assert!(output.contains("-75000 IDR"));
        assert!(output.contains("Expenses:5101-Makan-Minum"));
        assert!(output.contains("75000 IDR"));
    }
}
